### PR TITLE
Adabot Filename Hotfix

### PR DESCRIPTION
**Pull request by KeithCissell**
Discovered that when trying to launch rviz or gazebo simulations the launch files were looking for:
adabot/adabot_description/urdf/adabot.base.xacro
while this file was named:
adabot/adabot_description/urdf/adabot.xacro

Only change made was updating the filename, but I thought this should be taken care of asap so others don't run into the same issue when trying to launch a simulation.

### CODE REVIEW

**Comment by KeithCissell** [comment]
Looks like the Travis CI tests failed when trying to look for the old `adabot.xacro` file. It may be easier to change the launch files instead, but I think `adabot.base.xacro` better follows your naming convention.

**Comment by anthony-jclark** [comment]
I'm not sure which name is better. I don't really think `adabot.base.xacro` conveys the correct meaning, but `adabot.xacro` might not either. What about `adabot.main.xacro`?

**Comment by KeithCissell** [comment]
`adabot.main.xacro` sounds best to me. I can adjust the filename and launch file calls but I'm not sure how to update the testing so that it passes Travis CI.

**Comment by anthony-jclark** [comment]
I agree. Let's go with `adabot.main.xacro`. A good practice for whenever you change a file's name is to `grep` to see if the file's name appears anywhere. **I obviously did not do this when I changed the name, but I should have.**

`grep -r adabot.base.xacro *`

`grep -r adabot.xacro *`

**Comment by anthony-jclark** [comment]
@KeithCissell do you want to make the additional changes? (Looks like it's just '.travis.sh' that needs to be updated now.

**Comment by KeithCissell** [comment]
Hopefully that will do it! I've never messed with Travis before

**Pull request merged**
