### PR TITLE
Adabot Macro Abstraction

### PR DESCRIPTION
**Pull request by KeithCissell**
Just noticed I had some work that was done over the summer and didn't get merged in. I left off on a "TF" issue when trying to launch `rviz`, but it may have been fixed by an update. When attempted to launch it I had no problem. I would pull these changes down and test them yourself to be sure though.

Changes:
* Abstracted Macro files. Made a macro file for each individual joint type
* Added a "debug_visuals" parameter ([issue #16](https://github.com/anthonyjclark/adabot/issues/16))
* Adjusted the default parameter values
* Added a parameter to prepend "robot_name" to each joint to allow creation of multiple robots in a single environment

### CODE REVIEW

**Comment by KeithCissell** [comment]
Looks like the travis-ci test is failing because `catkin build` doesn't find any packages in /src. Do you know why that might be? I couldn't find much online.

**Comment by KeithCissell** [comment]
Looks like travis-ci is failing due to changes outside of this PR. I'll have to look into the dependencies in the travis client that's used.
Here is travis with the same failure when it was tested on the current version of master ([PR #22](https://github.com/anthonyjclark/adabot/pull/22)): https://travis-ci.org/anthonyjclark/adabot/builds/332900857?utm_source=github_status&utm_medium=notification

**Comment by KeithCissell** [comment]
_Note to self:_ Here are the diffs between the currently failing (left) and the previously working (right) setups/run on travis-ci: https://www.diffchecker.com/PDCXSDAi

**Comment by KeithCissell** [comment]
:tada: hallelujah it works :tada:

**Review by anthonyjclark — APPROVED** [review]

**Pull request merged**
