### PR TITLE
Variable Weg Parameter

### PR DESCRIPTION
**Pull request by KeithCissell**
Used conditional blocks to allow for a variable number of wegs to be added to each wheel.
The variable can be set in one place within the `adabot.main.xacro` file.
Right now the variable can be set for 0-8 wegs per wheel.

### CODE REVIEW

**Comment by KeithCissell** [comment]
Let me know if you want me to add any more parameters that could be adjusted via command line.

**Comment by KeithCissell** [comment]
I have the default parameters set up in the launch files, but they can each be set through `arg:=value` when calling the launch file. As for testing, I just made sure that it launched normally with default values and then that I could adjust each of the parameters with command line arguments.
I suppose I need to find some way to declare defaults within the xacro file itself looking at the checks that failed.

**Comment by anthony-jclark** [comment]
I would have thought that default values were only needed in the launch files. I'll take a look to see if I can find the issue.

**Comment by KeithCissell** [comment]
Okay, I was just thinking for if the .xacro file is used anywhere outside these two launch files

**Comment by anthony-jclark** [comment]
Ahh yes, that does make sense. Probably should make the change then.

**Comment by KeithCissell** [comment]
Okay, I will look into it tonight

**Comment by anthony-jclark** [comment]
I probably should have let you finish this pull request before I pushed my significant changes to the same files. Let me know if you have any trouble.

**Comment by KeithCissell** [comment]
From what I was researching, it doesn't look like there is a clean way to declare defaults for the parameters taking in arguments. So we are stuck with 2 options that I can think of:

1. We create conditional blocks that check for the existence of the arguments before setting it either to that arg value or the default. (The code would be a lot messier and harder to follow/maintain)
2. We assume that any file that launches the .xacro file will be passing in the required arguments. (This would mean that we need to update the test suite)

I lean towards option 2 myself. I can try to find another way by messing with the code. I haven't gotten the chance to try anything yet because of issues I've been having with the ZSH shell.

**Comment by anthony-jclark** [comment]
Would it make sense to have a new xacro file just for input arguments? All of the nasty logic could be kept there.

But as you say, it may be better to just go with what you already have and update the test itself (pretty simple addition to the `.tavis.sh` file). It is also unlikely that we will ever use the xacro files outside of launch files.

The downside of updating the test suite is that we now have even more things to update each time we add a command line argument (all launch files and the test script).

**Comment by KeithCissell** [comment]
I think if we kept all that logic in another xacro file we may run into the same issue when trying to pass those parameters into the main xacro file, but I could be wrong since they would be coming from another xacro instead of a launch file. 
I think for now we should update the tests and then we can look into a more solid solution if we find out that it would be useful. I will try to work on it tonight if I am able to get my environment pieced back together. If I'm unable to get to it I will ping you.

**Comment by anthony-jclark** [comment]
I did a bit of digging this morning and I think we should put default values in the xacro files. For example, this works fine for me and would not require much change to what we already have:

```xml
<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="test">

    <xacro:arg name="some_var" default="1"/>
    <xacro:property name="some_var" value="$(arg some_var)" />
    <test>${some_var * 10}</test>

</robot>
```
`rosrun xacro xacro --inorder test.xacro`

`rosrun xacro xacro --inorder test.xacro some_var:=2`

If we do it this way, we do not need to send set the values from every launch file. Some, if not most, launch files and tests should be fine with all default values.

**Comment by KeithCissell** [comment]
If that method works that is perfect for what we need. I wasn't able to get my environment working again last night, but I'll have more time tonight to mess with it.

**Comment by anthony-jclark** [comment]
Two more things to mention:

1. Since xacro files are combined using an "include" style that means that they are effectively all pasted together--meaning that we can put the `<xacro:arg>` and `<xacro:property>` elements in the parameters files and they can be used anywhere.

2. Since I made the mistake of pushing my changes before accepting your pull-request, I think it will be better if you pull master and merge on your end. **Note: I created a few new xacro files and moved things around, which is going to make it a huge pain in your ass to make sure that we don't lose anything during the merge. One possible strategy is to pull my changes and start from scratch on this pull-request. This might be a good idea since we will no longer need the launch file changes to be immediate.**

**Comment by anthony-jclark** [comment]
I am closing this because I ended up copying the parts of your repository that we needed and finished the solution. I'm not happy with it, but I'm not sure that there is an easier way. Check out 91d8d08cb21080ad20e3588ef092c6cb1bd4c89c, c0f7a8d6158e9d37cfe1d3c7b2de5087f6168a5e, and 4d3e284640bb1bfd3620173d2f2bbdc4809a60f2.

**Comment by KeithCissell** [comment]
Yeah that's not an ideal setup. I've got some time to work on things today and Ubuntu seems to be cooperating so I will see if I can't find a prettier solution.

**Pull request closed without merging**
